package com.rules;

import java.util.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * International Transaction Processing
 * Generated from DSL rule definition
 *
 * @generated template_code_generator.py v1.0.0
 * @complexity 1/10
 * @performance hot
 * @timestamp 2025-10-14T19:07:08Z
 */
public class InternationalTransactionProcessingRule {

    // ════════════════════════════════════════════════════════════════
    // Result Container
    // Generated by: standard_rule_template.py (identical across all rules)
    // ════════════════════════════════════════════════════════════════

    public static class RuleResult {
        private final boolean matched;
        private final List<String> actions;
        private final String finalAction;

        public RuleResult(boolean matched, List<String> actions, String finalAction) {
            this.matched = matched;
            this.actions = actions;
            this.finalAction = finalAction;
        }

        public boolean isMatched() { return matched; }
        public List<String> getActions() { return actions; }
        public String getFinalAction() { return finalAction; }
    }

    // ════════════════════════════════════════════════════════════════
    // Main Evaluation Logic
    // Generated by: template_code_generator.py::generate_code()
    // Template: standard_rule_template.py::generate_standard_rule()
    // ════════════════════════════════════════════════════════════════

    public static RuleResult evaluate(Map<String, Object> context) {
        // Initialization
        List<String> actions = new ArrayList<>();
        String finalAction = null;
        boolean matched = false;

        // Entity extraction (from DSL entities: account, transaction)
        Map<String, Object> account = (Map<String, Object>) context.get("account");
        Map<String, Object> transaction = (Map<String, Object>) context.get("transaction");

        // Rule logic
        if ((!_equals(_getFieldValue((Map<String, Object>)_getFieldValue((Map<String, Object>)transaction, "location"), "country"), "US")) && (_compareTo(_getFieldValue((Map<String, Object>)transaction, "amount"), _getFieldValue((Map<String, Object>)account, "internationalLimit")) <= 0)) {
            matched = true;
            actions.add("approveTransaction(" + _getFieldValue((Map<String, Object>)transaction, "amount") + ")");
            actions.add("applyForeignExchangeFee(" + (_toNumber(_getFieldValue((Map<String, Object>)transaction, "amount")) * 0.025) + ")");
            actions.add("updateAccountBalance(" + (_toNumber(_getFieldValue((Map<String, Object>)transaction, "amount")) + (_toNumber(_getFieldValue((Map<String, Object>)transaction, "amount")) * 0.025)) + ")");
        } else if ((!_equals(_getFieldValue((Map<String, Object>)_getFieldValue((Map<String, Object>)transaction, "location"), "country"), "US")) && (_compareTo(_getFieldValue((Map<String, Object>)transaction, "amount"), _getFieldValue((Map<String, Object>)account, "internationalLimit")) > 0)) {
            matched = true;
            actions.add("declineTransaction(" + "\"International transaction limit exceeded\"" + ")");
        } else {
            matched = true;
            actions.add("approveTransaction(" + _getFieldValue((Map<String, Object>)transaction, "amount") + ")");
        }

        return new RuleResult(matched, actions, finalAction);
    }

    // ════════════════════════════════════════════════════════════════
    // Standard Helper Methods (identical across all generated rules)
    // Template: standard_rule_template.py::get_helper_methods()
    // ════════════════════════════════════════════════════════════════

    // Helper method: Get field value with null safety
    private static Object _getFieldValue(Map<String, Object> entity, String fieldName) {
        return entity != null ? entity.get(fieldName) : null;
    }

    // Helper method: Null-safe equality comparison
    private static boolean _equals(Object a, Object b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        return a.toString().equals(b.toString());
    }

    // Helper method: Type-safe numeric comparison
    private static int _compareTo(Object a, Object b) {
        if (a == null || b == null) return 0;
        try {
            if (a instanceof Number && b instanceof Number) {
                return Double.compare(((Number)a).doubleValue(), ((Number)b).doubleValue());
            }
            return a.toString().compareTo(b.toString());
        } catch (Exception e) {
            return 0;
        }
    }

    // Helper method: Null-safe numeric conversion
    private static double _toNumber(Object obj) {
        if (obj == null) return 0.0;
        if (obj instanceof Number) return ((Number)obj).doubleValue();
        try {
            return Double.parseDouble(obj.toString());
        } catch (NumberFormatException e) {
            return 0.0;
        }
    }
}
